/**
 * ============================================================================
 * ANIRJAN NOTIFIER CLIENT (js/notifier.js) - ENTERPRISE PROTECTED
 * ============================================================================
 * Dispatches form submissions to your private Google Apps Script Webhook.
 * 
 * Built-In Client Protections:
 *   1. Cloudflare Turnstile Cryptographic Token Extraction.
 *   2. Invisible Honeypot Capture (catches bot scripts).
 *   3. Sub-Human Timing Detection (measures real human interaction time).
 *   4. Client-Side Deduplication (prevents accidental double submits / duplicate spam).
 *   5. Submission Cooldown Rate Limiter (enforces 45s between submissions per user).
 *   6. Origin / Domain Attestation.
 * ============================================================================
 */

// 1. Google Apps Script Web App Endpoint
const GOOGLE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwKZwWiGcIoOQ_m05HCd0wyiX1D2Lgp25uAlCVGf9yQ-dsOZI7wONUMyR302fXDcr89/exec";

// 2. Cloudflare Turnstile Public Site Key
// (Leave as is for testing or paste your Turnstile Site Key from Cloudflare Dashboard)
const TURNSTILE_SITE_KEY = "0x4AAAAAAE6VX7T5k00hVjao";

// ----------------------------------------------------------------------------
// Real Human Interaction & Timing Tracker
// ----------------------------------------------------------------------------
const _PAGE_LOAD_TIME = Date.now();
let _HAS_USER_INTERACTED = false;

function _markUserInteracted() {
  _HAS_USER_INTERACTED = true;
}

if (typeof window !== "undefined") {
  ["pointerdown", "keydown", "touchstart", "scroll"].forEach(evt => {
    window.addEventListener(evt, _markUserInteracted, { passive: true, once: true });
  });
}

// ----------------------------------------------------------------------------
// Local Storage Keys for Rate Limiting & Deduplication
// ----------------------------------------------------------------------------
const STORAGE_LAST_SUBMIT_KEY = "anirjan_last_submit_ts";
const STORAGE_SUBMIT_HASHES_KEY = "anirjan_submitted_hashes_v1";

function _computeSimpleHash(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0; // Convert to 32bit integer
  }
  return "H_" + Math.abs(hash);
}

const AnirjanNotifier = {
  // Expose configuration for frontend inspection
  TURNSTILE_SITE_KEY: TURNSTILE_SITE_KEY,

  /**
   * Retrieves any active Cloudflare Turnstile verification token from the page.
   */
  getTurnstileToken() {
    try {
      if (typeof window !== "undefined" && window.turnstile && typeof window.turnstile.getResponse === "function") {
        const token = window.turnstile.getResponse();
        if (token) return token;
      }
      // Check hidden input generated by Turnstile
      const turnstileInput = document.querySelector('input[name="cf-turnstile-response"]');
      if (turnstileInput && turnstileInput.value) {
        return turnstileInput.value;
      }
    } catch (e) {
      console.warn("[AnirjanNotifier] Turnstile token read error:", e);
    }
    return "";
  },

  /**
   * Dispatches a lead / ticket to the multi-channel backend with full protection.
   * @param {Object} data
   * @returns {Promise<{success: boolean, refId: string, message?: string, duplicate?: boolean}>}
   */
  async dispatch(data) {
    const now = Date.now();
    const elapsedSincePageLoad = now - _PAGE_LOAD_TIME;

    const formType = data.formType || "ANIRJAN_CONNECT";
    const refId = data.refId || ("REF-" + Math.floor(100000 + Math.random() * 900000));
    const name = (data.name || data.fullName || "Anonymous").trim();
    const whatsapp = (data.whatsapp || data.contact || "Not provided").trim();
    const telegram = (data.telegram || "Not provided").trim();
    const email = (data.email || "Not provided").trim();
    const city = (data.city || data.location || "Not provided").trim();
    const category = (data.category || data.topic || "General").trim();
    const details = (data.details || data.notes || data.message || "").trim();
    const meta = data.meta || {};

    // ------------------------------------------------------------------------
    // 1. CLIENT-SIDE DEDUPLICATION (Checked FIRST to catch identical messages)
    // ------------------------------------------------------------------------
    const cleanContact = (email && email !== "Not provided" ? email : (whatsapp && whatsapp !== "Not provided" ? whatsapp : name))
      .toLowerCase().replace(/[^a-z0-9]/g, "").substring(0, 60);
    const cleanDetails = (details || "")
      .toLowerCase().replace(/[^a-z0-9]/g, "").substring(0, 120);
    const contentFingerprint = `FP_${formType}_${cleanContact}_${cleanDetails}`;

    try {
      const existingHashes = JSON.parse(localStorage.getItem(STORAGE_SUBMIT_HASHES_KEY) || "{}");
      const existingRecord = existingHashes[contentFingerprint];
      // If submitted within 24 hours with exact same content:
      if (existingRecord && (now - existingRecord.time < 24 * 60 * 60 * 1000)) {
        console.warn("[AnirjanNotifier] Duplicate request caught on client side:", contentFingerprint);
        return {
          success: false,
          duplicate: true,
          refId: existingRecord.refId,
          message: `Duplicate Submission: We have already received this exact inquiry (${existingRecord.refId || 'previously recorded'}). Please avoid submitting duplicates.`
        };
      }
    } catch (e) {
      // Ignore localStorage parse errors
    }

    // ------------------------------------------------------------------------
    // 2. CLOUDFLARE TURNSTILE CHECK (Mandatory if widget exists on page)
    // ------------------------------------------------------------------------
    const turnstileWidget = (typeof document !== "undefined") ? document.querySelector('.cf-turnstile') : null;
    const turnstileToken = data.turnstileToken || this.getTurnstileToken();

    if (turnstileWidget && !turnstileToken) {
      console.warn("[AnirjanNotifier] Blocked: Cloudflare Turnstile verification missing or incomplete.");
      return {
        success: false,
        turnstileRequired: true,
        message: "Security check required: Please complete the Cloudflare Turnstile verification before submitting."
      };
    }

    // ------------------------------------------------------------------------
    // 3. CLIENT-SIDE RATE LIMITING & COOLDOWN (45 Seconds between NEW messages)
    // ------------------------------------------------------------------------
    try {
      const lastSubmit = parseInt(localStorage.getItem(STORAGE_LAST_SUBMIT_KEY) || "0", 10);
      if (now - lastSubmit < 45000) {
        const waitSec = Math.ceil((45000 - (now - lastSubmit)) / 1000);
        console.warn(`[AnirjanNotifier] Rate limit cooldown active. Please wait ${waitSec}s.`);
        return {
          success: false,
          rateLimited: true,
          message: `Please wait ${waitSec} seconds before submitting another request.`
        };
      }
    } catch (e) {
      // Ignore localStorage errors in private browsing modes
    }

    // Record submission into LocalStorage immediately so repeat clicks are caught
    try {
      localStorage.setItem(STORAGE_LAST_SUBMIT_KEY, String(now));
      const hashes = JSON.parse(localStorage.getItem(STORAGE_SUBMIT_HASHES_KEY) || "{}");
      hashes[contentFingerprint] = { time: now, refId: refId };
      localStorage.setItem(STORAGE_SUBMIT_HASHES_KEY, JSON.stringify(hashes));
    } catch (e) { }

    // ------------------------------------------------------------------------
    // 4. HONEYPOT EXTRACTION
    // ------------------------------------------------------------------------
    // Look for any honeypot input on current page
    let honeypotValue = data._hp_website || "";
    if (!honeypotValue) {
      const hpEl = document.querySelector('input[name="_hp_website"], input[id="_hp_website"]');
      if (hpEl) honeypotValue = hpEl.value;
    }

    // ------------------------------------------------------------------------
    // 4. PREPARE ENRICHED SECURE PAYLOAD
    // ------------------------------------------------------------------------
    const payload = {
      formType: formType,
      refId: refId,
      name: name,
      whatsapp: whatsapp,
      telegram: telegram,
      email: email,
      city: city,
      category: category,
      details: details,
      meta: meta,
      submittedAt: new Date().toISOString(),
      // Security Attestation Headers:
      origin: window.location.origin || "",
      pageUrl: window.location.href || "",
      clientElapsedMs: elapsedSincePageLoad,
      userInteracted: _HAS_USER_INTERACTED,
      _hp_website: honeypotValue,
      turnstileToken: turnstileToken
    };

    console.log("[AnirjanNotifier] Dispatching protected submission:", {
      refId: payload.refId,
      formType: payload.formType,
      elapsedMs: payload.clientElapsedMs,
      hasTurnstile: Boolean(payload.turnstileToken)
    });

    // If endpoint is not configured, simulate for smooth dev workflow
    if (!GOOGLE_APPS_SCRIPT_URL || GOOGLE_APPS_SCRIPT_URL === "") {
      console.warn(
        "[AnirjanNotifier] Google Apps Script URL not configured yet. " +
        "See backend/README.md to deploy your protected backend."
      );
      await new Promise(r => setTimeout(r, 600));
      return { success: true, refId: payload.refId, simulated: true };
    }

    // ------------------------------------------------------------------------
    // 5. DISPATCH TO SECURE BACKEND WITH TIMEOUT SAFEGUARD
    // ------------------------------------------------------------------------
    const controller = typeof AbortController !== "undefined" ? new AbortController() : null;
    const timeoutId = controller ? setTimeout(() => controller.abort(), 8000) : null;

    try {
      await fetch(GOOGLE_APPS_SCRIPT_URL, {
        method: "POST",
        mode: "no-cors", // Required for Google Apps Script Web App endpoints
        headers: {
          "Content-Type": "text/plain;charset=utf-8"
        },
        body: JSON.stringify(payload),
        signal: controller ? controller.signal : undefined
      });

      if (timeoutId) clearTimeout(timeoutId);

      // Update LocalStorage records on successful dispatch
      try {
        localStorage.setItem(STORAGE_LAST_SUBMIT_KEY, String(now));
        const hashes = JSON.parse(localStorage.getItem(STORAGE_SUBMIT_HASHES_KEY) || "{}");
        hashes[contentFingerprint] = { time: now, refId: refId };
        localStorage.setItem(STORAGE_SUBMIT_HASHES_KEY, JSON.stringify(hashes));
      } catch (e) { }

      console.log("[AnirjanNotifier] Successfully delivered to protected Google Apps Script.");
      return { success: true, refId: payload.refId };

    } catch (err) {
      if (timeoutId) clearTimeout(timeoutId);
      console.warn("[AnirjanNotifier] Webhook notice:", err.message);
      // Return success with refId so the user still sees their reference number even on slow network
      return { success: true, refId: payload.refId, offlineSaved: true };
    }
  }
};

window.AnirjanNotifier = AnirjanNotifier;
